### ISSUE TITLE
Select back-end framework

### ISSUE THREAD

**Issue by aptiko** [aptiko/irma#3]
We can use Django+DRF or flask for the back-end.

Benefits of Django+DRF are maturity, migrations, admin site, batteries included.

Benefits of flask are that it's easier.

If someone tells you "I'm a Django developer", you more or less know what he means. But if someone tells you "I'm a flask developer", go figure: do they know `pony` or `peewee` or `SQLAlchemy`? And so on.

On the other hand, even a Django developer doesn't necessarily know it all, as Django+DRF is huge. It can be easier to train a flask developer to the things he doesn't know than a Django developer.

I think we've spelled out all benefits and drawbacks, so there's not much use arguing any more about it. We just need to make a decision.

Probably the decision will be Django because @aptiko is more comfortable and will help with the backend (possibly undertake it entirely) and he has another Django project (OpenHI/Enhydris) running at the same time.

**Comment by kickapoo** [comment]
In contrast 

Flask:
- Micro framework, not magic (or many middleware magic)
- Quick learning curve
- Stable release (one of issues with Django is to follow new releases)
- Support Extensions like (https://pythonhosted.org/Flask-JWT/)
- Support large scale apps (blueprints)
- The trend is Django Developers to switch to Flask and not other way.
- No need for Restfull extensions, has MethodView (http://flask.pocoo.org/docs/1.0/views/#method-views-for-apis) 

Pony:
- queries to the database using Python generator expressions.
- hooks during CRUD: https://docs.ponyorm.com/api_reference.html#entity-hooks 
- migration tool on the way for release: https://github.com/ponyorm/pony/issues/16 
- Json support
- db.Model (in Pony called db.Entity) as python standard types: https://docs.ponyorm.com/api_reference.html#attribute-data-types
-  Only (3) three option for a field: Required, Optional, Set (db relation one to many)
-  Field validation in glamor (https://docs.ponyorm.com/api_reference.html?highlight=lazy#cmdoption-arg-py-check)


My personal choice is Flask / Pony
